/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yang' at '12/9/15 3:05 PM' with Gradle 2.5
 *
 * @author yang, @date 12/9/15 3:05 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
